#TABUADA:
v = int(input(print('Digite um número para ver sua tabuada: ')))
t1 = v * 1
t2 = v * 2
t3 = v * 3
t4 = v * 4
t5 = v * 5
t6 = v * 6
t7 = v * 7
t8 = v * 8
t9 = v * 9
t10 = v * 10
print('{} * 1 = {}'.format(v, t1))
print('{} * 2 = {}'.format(v, t2))
print('{} * 3 = {}'.format(v, t3))
print('{} * 4 = {}'.format(v, t4))
print('{} * 5 = {}'.format(v, t5))
print('{} * 6 = {}'.format(v, t6))
print('{} * 7 = {}'.format(v, t7))
print('{} * 8 = {}'.format(v, t8))
print('{} * 9 = {}'.format(v, t9))
print('{} * 10 = {}'.format(v, t10))
